import { Header } from "@components/Header";
import type { Metadata } from "next";
import { Sen } from "next/font/google";

import "@styles/globals.scss";

export const metadata: Metadata = {
  title: "Modsen Client Blog",
  description: "Generated by create next app",
};

const sen = Sen({
  subsets: ["latin"],
  variable: "--font-san",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sen.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
