import "@styles/globals.scss";

import type { Metadata } from "next";
import { Sen } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

import { Footer } from "@components/footer/footer";
import { Header } from "@components/header/header";

export const metadata: Metadata = {
  title: "Modsen Client Blog",
  description: "Generated by create next app",
};

const sen = Sen({
  subsets: ["latin"],
  variable: "--font-san",
});

type RootLayoutProps = Readonly<{
  children: React.ReactNode;
  params: {
    locale: string;
  };
}>;

export default async function LocaleLayout({
  children,
  params: { locale },
}: RootLayoutProps) {
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={`${sen.variable}`}>
        <NextIntlClientProvider messages={messages}>
          <Header />
          {children}
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
